pipeline {
    agent any
    parameters {
        string defaultValue: '', description: 'Username to create', name: 'USER', trim: true
        string defaultValue: '', description: 'Password for the user', name: 'PASSWORD', trim: true
    }
    stages {
        stage ('Creating User') {
            steps {
                    script {
                    def username = $USER
                    def password = $PASSWORD

                    def instance = jenkins.model.Jenkins.instance
                    def hudsonRealm = instance.getSecurityRealm()

                    def newUser = hudsonRealm.createAccount(username, password)
                    newUser.save()

                    echo "Jenkins user '${username}' created successfully."
                    }
            }
        }
    }
}